Vagrant.configure("2") do |config|
    config.vm.define "scriptbox" do |scriptbox|    
    scriptbox.vm.box = "spox/ubuntu-arm"
    scriptbox.vm.network "private_network", ip: "192.168.56.26"
    scriptbox.vm.hostname = "scriptbox"
    host_path = "."
    guest_path = "/vagrant"
    scriptbox.vm.synced_folder host_path, guest_path
    scriptbox.vm.provider "vmware_desktop" do |v|
      v.allowlist_verified = true
      v.ssh_info_public = true
      v.gui = true
    end
    scriptbox.vm.provision "shell", inline: <<-SHELL
    sudo mv /etc/apt/sources.list.d/* /tmp/
    sudo apt clean
    sudo apt update
    sudo ufw stop
    SHELL
  end
    config.vm.define "web01" do |web01|    
    web01.vm.box = "spox/ubuntu-arm"
    web01.vm.network "private_network", ip: "192.168.56.27"
    web01.vm.hostname = "web01"
    host_path = "."
    guest_path = "/vagrant"
    web01.vm.synced_folder host_path, guest_path
    web01.vm.provider "vmware_desktop" do |v|
      v.allowlist_verified = true
      v.ssh_info_public = true
      v.gui = true
    end
    web01.vm.provision "shell", inline: <<-SHELL
    sudo mv /etc/apt/sources.list.d/* /tmp/
    sudo apt clean
    sudo apt update
    sudo ufw stop
    SHELL
  end
    config.vm.define "web02" do |web02|    
    web02.vm.box = "spox/ubuntu-arm"
    web02.vm.network "private_network", ip: "192.168.56.28"
    web02.vm.hostname = "web02"
    host_path = "."
    guest_path = "/vagrant"
    web02.vm.synced_folder host_path, guest_path
    web02.vm.provider "vmware_desktop" do |v|
      v.allowlist_verified = true
      v.ssh_info_public = true
      v.gui = true
    end
    web02.vm.provision "shell", inline: <<-SHELL
    sudo mv /etc/apt/sources.list.d/* /tmp/
    sudo apt clean
    sudo apt update
    sudo ufw stop
    SHELL
  end
    config.vm.define "web03" do |web03|    
    web03.vm.box = "spox/ubuntu-arm" 
    web03.vm.box_version = "1.0.0"
    web03.vm.network "private_network", ip: "192.168.56.29"
    web03.vm.hostname = "web03"
    host_path = "."
    guest_path = "/vagrant"
    web03.vm.synced_folder host_path, guest_path
    web03.vm.provider "vmware_desktop" do |v|
      v.allowlist_verified = true
      v.ssh_info_public = true
      v.gui = true
    end
  end
end
