apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    name: vproapp
spec:
  containers:
    - name: appcontainer
      image: nginx
      ports:
        - name: vproapp-port
          containerPort: 80