apiVersion: v1 
kind: Service
metadata:
  name: helloworld-service
spec:
  selector: 
      name: vproapp
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 80
      protocol: TCP


